<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AssemblyVersion>3.7.2.0</AssemblyVersion>
    <FileVersion>3.7.2.0</FileVersion>
    <Copyright>Copyright ©  2019-2022 Zebedee Mason</Copyright>
    <Company>Zebedee Mason</Company>
    <Version>3.7.2</Version>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <LangVersion>latest</LangVersion>
    <Authors>zebmason</Authors>
    <Description>Parser for project files</Description>
    <PackageProjectUrl>https://github.com/zebmason/ProjectIO</PackageProjectUrl>
    <RepositoryUrl>https://github.com/zebmason/ProjectIO</RepositoryUrl>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="docs\readme.md" Pack="true" PackagePath=""/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ProjectIO.Core\ProjectIO.Core.csproj" />
  </ItemGroup>

</Project>
